# Generated by Django 4.2.14 on 2024-07-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest_pdf_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anushuchifourteen',
            name='DFO_officer_signature',
            field=models.TextField(),
        ),
    ]
