# Generated by Django 5.0.6 on 2024-07-10 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest_pdf_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anushuchifourteen',
            name='details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forest_pdf_app.details'),
        ),
    ]
