# Generated by Django 5.0.6 on 2024-07-10 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest_pdf_app', '0002_anushuchifourteen_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anushuchifourteen',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forest_pdf_app.details'),
        ),
    ]
