# Generated by Django 4.2.14 on 2024-07-13 16:37

from django.db import migrations
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forest_pdf_app', '0002_alter_anushuchifourteen_dfo_officer_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anushuchifourteen',
            name='DFO_officer_signature',
            field=jsignature.fields.JSignatureField(),
        ),
    ]
