# Generated by Django 5.0.6 on 2024-07-10 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forest_pdf_app', '0003_alter_anushuchifourteen_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anushuchifourteen',
            name='division_forest_office',
        ),
    ]
