# Generated by Django 4.2.14 on 2024-07-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest_pdf_app', '0003_alter_anushuchifourteen_dfo_officer_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anushuchifourteen',
            name='DFO_officer_signature',
            field=models.TextField(null=True),
        ),
    ]
