# Generated by Django 5.0.6 on 2024-07-10 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangonepal', '0003_initial'),
        ('forest_pdf_app', '0004_remove_anushuchifourteen_division_forest_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='anushuchifourteen',
            name='division_forest_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangonepal.district'),
        ),
    ]
