# Generated by Django 4.2.14 on 2024-07-10 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forest_pdf_app', '0006_alter_anushuchifourteen_division_forest_office'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anushuchifourteen',
            old_name='dfo_officer_signature',
            new_name='DFO_officer_signature',
        ),
    ]
