# Generated by Django 4.2.14 on 2024-07-10 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forest_pdf_app', '0007_rename_dfo_officer_signature_anushuchifourteen_dfo_officer_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anushuchifourteen',
            name='details',
        ),
        migrations.AddField(
            model_name='details',
            name='anusuchi_cha_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forest_pdf_app.anushuchifourteen'),
        ),
    ]
