# Generated by Django 4.2.14 on 2024-07-10 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forest_pdf_app', '0009_anushuchifourteen_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anushuchifourteen',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
